services:
  app:
    build:
      context: ./codigo-fonte
    container_name: wordnet-app
    ports:
      - "3000:3000"
    volumes:
      - ./codigo-fonte:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: loja_computadores
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: wordnet-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_computadores
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./codigo-fonte/init-db-scripts:/docker-entrypoint-initdb.d

  relatorios:
    build:
      context: ./relatorios
    container_name: relatorios-service
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: loja_computadores
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
